let books = [
    { 

        title: 'Little prince',
        author: 'Antoine de Saint-Exupéry',
        gender: 'literature', 
        language: 'English',
        price: 20000,
        format: 'ebook',
        isbn: '9109109', 
        description: 'is a timeless tale about a young prince who explores the universe, learning profound lessons about love, friendship, and the human condition along the way', 
        status: 'new', 
        location: 'Sena Comercio y Turismo', 
        publication_date: 'April 6, 1943', 
        editorial: 'Reynal & Hitchcock', 
        pages: 100

    },    
    {
        title: 'The Great Gatsby',
        author: 'F. Scott Fitzgerald',
        genre: 'Tragedy',
        language: 'English',
        price: 40000,
        format: 'ebook',
        isbn: '9780743273565',
        description: 'A mesmerizing tale of love, wealth, and ambition set against the backdrop of the Roaring Twenties in America.',
        status: 'new',
        location: 'Sena Comercio y Turismo',
        publication_date: 'April 10, 1925',
        editorial: 'Scribner',
        pages: 180
    },
    {
        Title: 'The Hobbit',
        Author: 'J.R.R. Tolkien',
        Genre: 'Adventure',
        Language: 'English',
        Price: 60000,
        Format: 'ebook',
        ISBN: '9780345339683',
        Description: 'An enchanting tale of Bilbo Baggins, a hobbit who embarks on a grand adventure to reclaim treasure guarded by the fearsome dragon Smaug.',
        Status: 'New',
        Location: 'Sena Comercio y Turismo',
        Publication_Date: 'September 21, 1937',
        Editorial: 'Houghton Mifflin Harcourt',
        pages: 310
    },
    {
        Title: 'The Lord of the Rings',
        Author: 'J.R.R. Tolkien',
        Genre: 'Epic',
        Language: 'English',
        Price: 30000,
        Format: 'ebook',
        ISBN: '9780618640157',
        Descrition: 'A sweeping epic that follows Frodo Baggins and his companions on a perilous quest to destroy the One Ring and defeat the dark lord Sauron.',
        Status: 'New',
        Location: 'Sena Comercio y Turismo',
        Publication_Date: 'October 20, 1955',
        Editorial: 'Houghton Mifflin Harcourt',
        pages: 1178
    },
    {
        Title: 'Cien años de soledad',
        Author: 'Gabriel García Márquez',
        Genre: 'Fiction',
        Language: 'Spanish',
        Price: 100000,
        Format: 'ebook',
        ISBN: '9780307474728',
        Description: 'A landmark novel in Latin American literature, "Cien años de soledad" tells the multi-generational story of the Buendía family in the fictional town of Macondo, blending elements of magic and reality to create a rich tapestry of Latin American history and culture',
        Status: 'New',
        Location: 'Sena Comercio y Turismo',
        Publication_Date: 'May 30, 1967',
        Editorial: 'Vintage Español',
        pages: 417
    },
    {
        Title: 'The Alchemist',
        Author: 'Paulo Coelho',
        Genre: 'Fiction',
        Language: 'English',
        Price: 20000,
        Format: 'ebook',
        ISBN: '9780062315007',
        Description: 'A philosophical novel about a young Andalusian shepherd named Santiago who sets out on a journey to discover his Personal Legend, encountering various challenges and learning profound lessons about life, destiny, and the importance of following one\'s dreams.',
        Status: 'New',
        Location: 'Sena Comercio y Turismo',
        Publication_Date: '1988',
        Editorial: 'HarperOne',
        pages: 208
    },
    {
        Title: 'The Catcher in the Rye',
        Author: 'J.D. Salinger',
        Genre: 'Fiction',
        Language: 'English',
        Price: 20000,
        Format: 'ebook',
        ISBN: '9780316769488',
        Description: 'A classic coming-of-age novel that follows Holden Caulfield, a disenchanted teenager, as he navigates the complexities of adolescence and society in New York City.',
        Status: 'New',
        Location: 'Sena Comercio y Turismo',
        Publication_Date: 'July 16, 1951',
        Editorial: 'Little, Brown and Company',
        pages: 224
    },
    {
        Title: 'Love in the Time of Cholera',
        Author: 'Gabriel García Márquez',
        Genre: 'Romance',
        Language: 'Spanish',
        Price: 70000,
        Format: 'ebook',
        ISBN: '9780307389732',
        Description: 'A captivating tale of unrequited love, enduring passion, and the passage of time, set in a Caribbean port town and spanning over 50 years of Colombian history.',
        Status: 'New',
        Location: 'Sena Comercio y Turismo',
        Publication_Date: '1985',
        Editorial: 'Vintage Español',
        pages: 368
    },
    {
        Title: 'Chronicle of a Death Foretold',
        Author: 'Gabriel García Márquez',
        Genre: 'Mystery',
        Language: 'Spanish',
        Price: 45000,
        Format: 'ebook',
        ISBN: '9781400034710',
        Description: 'A gripping exploration of honor, morality, and fate, this novella tells the story of a murder in a small Colombian town and the events leading up to it.',
        Status: 'New',
        Location: 'Sena Comercio y Turismo',
        Publication_Date: '1981',
        Editorial: 'Vintage Español',
        pages: 128
    },
    {
        Title: 'The Sound of Things Falling',
        Author: 'Juan Gabriel Vásquez',
        Genre: 'Historical',
        Language: 'Spanish',
        Price: 87000,
        Format: 'ebook',
        ISBN: '9781594487484',
        Description: 'Set in Colombia during the turbulent 1990s, this novel delves into the aftermath of Pablo Escobar\'s reign and its impact on individuals and society, exploring themes of memory, guilt, and redemption.',
        Status: 'New',
        Location: 'Sena Comercio y Turismo',
        Publication_Date: '2011',
        Editorial: 'Riverhead Books',
        pages: 320
    },     
  ];

const presspages = () => books.filter(book => book.pages >= 200)

// console.log(presspages())
console.log(books.length)
console.log(books.forEach( book => console.log(book.pages) ))

